name: Deploy to EC2 on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2 and update Docker container
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop aws_web || true
            docker rm aws_web || true
            docker image rm ${{ secrets.DOCKER_USERNAME }}/aws_web:latest || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/aws_web:latest
            docker run -d -p 3000:3000 --name aws_web ${{ secrets.DOCKER_USERNAME }}/aws_web:latest
