name: Build and Deploy to EC2 on push to main

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/aws_web:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/aws_web:latest

      - name: SSH into EC2 and update Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/aws_web:latest"
            CONTAINER_IDS=$(docker ps -q --filter "ancestor=$IMAGE_NAME")
            if [ ! -z "$CONTAINER_IDS" ]; then
              docker stop $CONTAINER_IDS
              docker rm $CONTAINER_IDS
            fi
            IMAGE_ID=$(docker images -q $IMAGE_NAME)
            if [ ! -z "$IMAGE_ID" ]; then
              docker rmi $IMAGE_ID
            fi
            docker pull $IMAGE_NAME
            docker run -d -p 3000:3000 --name aws_web $IMAGE_NAME
